[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
ffi = true # if you set ffi to true that means you re going to allow foundry to run commands directly on your machine

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
